### ISSUE TITLE
globalVars in lessOptions

### ISSUE THREAD

**Issue by tdegrunt** [gabrielgrant/broccoli-less-single#11]
I'm trying to set globalVars in the following manner:
```javascript
lessOptions: {
  globalVars: {
    'theme': 'colorful'
  }
}
```
to later do something like this in the app.less:
```less
@import "theme-@{theme}.less";
```
But the globalVar doesn't seem to be defined, or is lessOptions not allowing globalVars?

See:
http://lesscss.org/features/#variables-feature-urls
http://lesscss.org/usage/#using-less-in-the-browser-relativeurls

**Comment by jasonmit** [comment]
Closing as fixed
