### ISSUE TITLE
Not respecting outputPaths config in Brocfile.js

### ISSUE THREAD

**Issue by lukesargeant** [gabrielgrant/broccoli-less-single#15]
i'm using ember-cli 0.1.5,

I'd like to build a css file for each 'skin-*.less' file in the app/styles folder. This works with plain CSS using the following config in my Brocfile.js:

```
var app = new EmberApp({
    outputPaths: {
        app: {
            css: {
                'skin-light': '/assets/skin-light.css',
                'skin-dark': '/assets/skin-dark.css'
            }
        }
    }
});
```

After installing the LESS precompiler with 'ember install:addon ember-cli-less' this config is not respected and instead 'ember build' looks for app/styles/app.less.

**Comment by jasonmit** [comment]
This should be fixed on master.  Could you verify?

—

**Comment by lukesargeant** [comment]
Thanks for the quick response,

I copied index.js from broccoli-less-single master into my project but it's still reporting the same error when I ember build:

```
Build failed.
File not found: /app/styles/app.less
in any of the following include paths:
```
It shouldn't be looking for that file at all, it should be looking for /app/styles/skin-light.less AND /app/styles/skin-dark.less as per my config for css:
```
var app = new EmberApp({
    outputPaths: {
        app: {
            css: {
                'skin-light': '/assets/skin-light.css',
                'skin-dark': '/assets/skin-dark.css'
            }
        }
    }
});
```

**Comment by jasonmit** [comment]
The build fail is likely an upstream issue in ember-cli-less:
https://github.com/gdub22/ember-cli-less/blob/master/index.js#L7-L17

If you do not specify an inputPath it defaults to app.less.  In any case, I can investigate over the weekend and track this issue down.

**Comment by rwwagner90** [comment]
@jasonmit how do I specify an inputPath?

**Comment by jasonmit** [comment]
@rwwagner90 the second argument is the input file path.

**Comment by jasonmit** [comment]
Closing as this should be fixed
