### ISSUE TITLE
Upgrade broccoli-caching-writer dependency

### ISSUE THREAD

**Issue by notmessenger** [gabrielgrant/broccoli-less-single#34]
According to https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md the `broccoli-caching-writer` dependency should be at `^2.2.1`

**Comment by jasonmit** [comment]
https://github.com/gabrielgrant/broccoli-less-single/blob/master/package.json#L39

**Comment by jasonmit** [comment]
^2.0.0 is a range (caret) constraint. It means that it will match >=2.0.0 <3.0.0.
