### ISSUE TITLE
An issue with less.js

### ISSUE THREAD

**Issue by knownasilya** [gabrielgrant/broccoli-less-single#35]
https://github.com/less/less.js/issues/2896

Seems like we can avoid by releasing a version that limits to v2.6 of Less?

**Comment by jasonmit** [comment]
Yup, will fix tonight if no one else gets to it.

**Comment by jasonmit** [comment]
0.6.1 locks less to < 2.7.0.  I'll unlock it once the issue is fixed.

**Comment by jasonmit** [comment]
2.7.1 was released, unlocked as 0.6.2
