### ISSUE TITLE
rebuilding despite no .less file changes

### ISSUE THREAD

**Issue by efx** [gabrielgrant/broccoli-less-single#44]
This continues discussion here https://github.com/gabrielgrant/broccoli-less-single/pull/31.
As a developer, I expect the less compiler to execute only when I change a `less` file in my project. This appears to not be the case. I took the following screenshot of performance output from ember-cli while running `ember server` and changing an `.hbs` file.
<img width="591" alt="screen shot 2018-10-31 at 11 30 33" src="https://user-images.githubusercontent.com/472721/47799316-66d87380-dd00-11e8-9798-2e45d1e60521.png">
```
 npm ls broccoli-less-single

myproject
└─┬ ember-cli-less@2.0.1
  └── broccoli-less-single@1.0.1
ember-cli: 3.5.0
node: 8.11.4
os: darwin x64
```

**Comment by efx** [comment]
To see specific debugging output `DEBUG="broccoli-caching-writer:LessCompiler" ember build`

**Comment by jasonmit** [comment]
@stefanpenner would this be resolved by implementing CachingWriter's `cacheInclude` option?  Anything I'm overlooking?

Thanks!

**Comment by jasonmit** [comment]
I'll need to investigate what it will take to resolve this, may be as simple as opting into `cacheInclude` within the super class `broccoli-caching-writer`.

**Comment by efx** [comment]
@jasonmit sweet, thank you! I can help dig in as well / test any PR.

**Comment by knownasilya** [comment]
@jasonmit just wondering if you had a chance to look at this more

**Comment by jasonmit** [comment]
@knownasilya I recall awhile back looking into this and believe this way be an upstream bug in ember-cli.

**Comment by jasonmit** [comment]
Just to re-iterate, I believe this isn't an issue since you can pass in `cacheInclude: []` which should skip the build step and use the cache result..

```js
const compileLess = require('broccoli-less-single');

const outputNode = compileLess(inputNodes, inputFile, outputFile, {
  cacheInclude: [/.*\.(css|less)$/]
});
```

We could make this the default or the callers like ember-cli-less can make them their own defaults.  For now, I'm going to close this unless there's anymore work needed.

**Comment by knownasilya** [comment]
Updated in ember-cli-less

**Comment by jasonmit** [comment]
I should have added, if this pops up again, feel free to create a new issue.  Thanks @knownasilya !
