### ISSUE TITLE
Improvements to errors.

### ISSUE THREAD

**Issue by WMeldon** [gabrielgrant/broccoli-less-single#5]
This plugin currently kills any long running services that might call it and throws out errors of mixed quality.  

I threw together a quick and dirty solution to both issues here: https://github.com/WMeldon/broccoli-less-single/tree/better-errors 

It's currently a fork of the cache fork so I'm not opening a pull request just yet.

**Comment by jasonmit** [comment]
Closing as a dupe to #7.
