### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by denisnazarov** [gabrielgrant/broccoli-less-single#7]
Having syntax errors in your less causes ember-cli server to crash. This also happens when you import less files that don't exist yet.

```javascript
file changed editor.less
file changed styles/editor.less
ParseError: Unrecognised input in .../tmp/tree_merger-tmp_dest_dir-W7qmEPWo
.tmp/app/styles/editor.less on line 19, column 9:
18         height: 100px; 
19         background-color #cccccc;
20       }

var css = tree.toCSS(lessOptions);                                                                          
TypeError: Cannot call method 'toCSS' of undefined
```

cc @rjackson @stefanpenner

**Comment by timohofmeijer** [comment]
@gabrielgrant It's quite a pain that every less error break the ember-cli server. @lfridael ’s fix works just fine. Would it be possible to merge this in?

**Comment by mntnoe** [comment]
I am experiencing the same problem. A merge of lfridael's fix would be appreciated.

**Comment by jasonmit** [comment]
Agreed, will take this up today

**Comment by timohofmeijer** [comment]
That would be awesome! Many thanks!

**Comment by jasonmit** [comment]
Does anyone know how to reproduce this with master?  I can't get broccoli to terminate on a less render exception.  It's also reporting errors as expected.

It's possible this was eliminated when we upgraded the LESS parser.

```sh
ParseError: Unrecognised input in /home/jasonmit/projects/less-example/tmp/tree_merger-tmp_dest_dir-Lss7wOCx.tmp/styles/app.less on line 21, column 10:
20 		.box-shadow(0 0 5px, 30%)
21 		padding: 10px;
22 	}
```

**Comment by mntnoe** [comment]
I think the problem might have disappeared when using less v2.4.0.

**Comment by jasonmit** [comment]
That's what I was also thinking.  Will keep the issue opened until I confirm ember cli also does not terminate.

**Comment by timohofmeijer** [comment]
So if I'd run from master, it wouldn’t crap out? Would it be possible to release a version where the `less` dependency is at `2.4.0` then?

transcript:
![screen shot 2015-03-03 at 11 22 19](https://cloud.githubusercontent.com/assets/1086519/6460455/aa4c2fea-c197-11e4-8bd8-b8cf71fd552e.png)

**Comment by jasonmit** [comment]
@timohofmeijer for my sanity before cutting a release, can you copy the index.js from master into `node_modules/broccoli-less-single/index.js` to verify it solves this elusive issue.

**Comment by timohofmeijer** [comment]
When I just replace `node_modules/broccoli-less-single/index.js` it wont run. When I also replace `node_modules/broccoli-less-single/package.json` install the packages it is solved.

`package.json` states `broccoli-less-single` version `0.2.0`, is this also supposed to be published to npm?

**Comment by jasonmit** [comment]
@timohofmeijer thanks for verifying that swapping out broccoli-less-single with the latest solved the problem :+1: 

I will publish 0.2.0 tonight

**Comment by jasonmit** [comment]
0.2.0 release and should mark this as resolved.

Thanks everyone

**Comment by timohofmeijer** [comment]
Sweet! Thanks a lot @jasonmit

**Comment by bware225** [comment]
@jasonmit So I'm having an issue with Less errors breaking my server, and not being logged to the console. I made an example project on my account that can be found here https://github.com/bware225/EmberExampleLessBreaking, and the error in the less file can be found here https://github.com/bware225/EmberExampleLessBreaking/blob/master/app/styles/app.less . Do you know of a way to stop the Less error from breaking the server and just log it to the console? I am using the 1.2.0 version of ember-cli-less. Thanks!

**Comment by jasonmit** [comment]
It really depends on what version ember cli less is pulling in if broccoli less single.  I will look at your project today and do some digging.




Thanks



—

**Comment by jasonmit** [comment]
@bware225 this was a downstream npm breaking change issue with `ramraf`.  Follow the directions here: https://github.com/ember-cli/ember-cli/issues/3413

Summary:
* remove node_modules (it didn't work otherwise for me)
* add ramraf 2.8.8 as a dependency (not a devdep)
* npm install

**Comment by bware225** [comment]
@jasonmit So after trying what you said there is some progress, instead of my server crashing it just outputs:
```
ParseError: Unrecognised input. Possibly missing something in /Users/bware/src/pardot/web/assets/nurtureStudio/tmp/tree_merger-tmp_dest_dir-pkZnvo9S.tmp/app/styles/line-area.less on line 14, column 6:
13 }
14 Error

```

Where it gives the file name line number and text on the line with the error (yay!). However, my server won't load any new pages or refresh the current one. Is anyone else experiencing this?
